Add the ability to select the debugger engines to connect to
MarcinJuraszek/WacVsTools pull request #3
Opened 2018-01-21 15:06 UTC by yitzhaks

This includes a new dialog which presents the available engines, similar to the Visual Studio dialog. The default is still to use the default engine.

2018-01-21 17:09 UTC, MarcinJuraszek requested changes

2018-01-21 17:09 UTC, MarcinJuraszek commented on src/WacVsTools.Core/AttachToWacProcess/AttachToWacProcessDialog.xaml.cs
> +        private HashSet<int> m_selectedProcesses;
please don't use `m_` when naming fields.

2018-01-21 17:09 UTC, MarcinJuraszek commented on src/WacVsTools.Core/AttachToWacProcess/SelectDebuggerEngineDialogModel.cs
> +        private bool m_isSelected;
nit: `m_`

2018-01-21 17:09 UTC, MarcinJuraszek commented on src/WacVsTools.Core/AttachToWacProcess/SelectDebuggerEngineDialogModel.cs
> +        private readonly bool m_isLazy;
`m_`

2018-01-21 17:31 UTC, yitzhaks commented on src/WacVsTools.Core/AttachToWacProcess/AttachToWacProcessDialog.xaml.cs
> +        private HashSet<int> m_selectedProcesses;
:(

2018-01-22 00:39 UTC, MarcinJuraszek approved these changes

2018-01-22 00:39 UTC, merged